// <auto-generated />
namespace RMS_System.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class grosstotaladded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(grosstotaladded));
        
        string IMigrationMetadata.Id
        {
            get { return "202203121046084_grosstotaladded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
