// <auto-generated />
namespace RMS_System.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class kitchendashbaordfixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kitchendashbaordfixed));
        
        string IMigrationMetadata.Id
        {
            get { return "202202251435437_kitchendashbaordfixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
